import type { Config } from "tailwindcss";

const config = {
	darkMode: ["class"],
	content: [
		"./pages/**/*.{ts,tsx}",
		"./components/**/*.{ts,tsx}",
		"./app/**/*.{ts,tsx}",
		"./src/**/*.{ts,tsx}",
	],
	prefix: "",
	theme: {
		container: {
			center: true,
			padding: "2rem",
			screens: {
				"2xl": "1400px",
			},
		},
		extend: {
			keyframes: {
				"accordion-down": {
					from: { height: "0" },
					to: { height: "var(--radix-accordion-content-height)" },
				},
				"accordion-up": {
					from: { height: "var(--radix-accordion-content-height)" },
					to: { height: "0" },
				},
			},
			animation: {
				"accordion-down": "accordion-down 0.2s ease-out",
				"accordion-up": "accordion-up 0.2s ease-out",
			},
			fontFamily: {
				"public-sans": "'Public Sans', sans-serif",
				barlow: "'Barlow', sans-serif",
				"geist-sans": ["var(--font-geist-sans)"],
				"geist-mono": ["var(--font-geist-mono)"],
			},
			colors: {
				white: "#ffffff",
				black: "#000000",
				"primary-lighter": "#D0ECFE",
				"primary-light": "#73BAFB",
				"primary-main": "#1877F2",
				"primary-dark": "#0C44AE",
				"primary-darker": "#042174",
				"secondary-lighter": "#EFD6FF",
				"secondary-light": "#C684FF",
				"secondary-main": "#8E33FF",
				"secondary-dark": "#5119B7",
				"secondary-darker": "#27097A",
				"info-lighter": "#CAFDF5",
				"info-light": "#61F3F3",
				"info-main": "#00B8D9",
				"info-dark": "#006C9C",
				"info-darker": "#003768",
				"success-lighter": "#C8FAD6",
				"success-light": "#5BE49B",
				"success-main": "#00A76F",
				"success-dark": "#007867",
				"success-darker": "#004B50",
				"warning-lighter": "#FFF5CC",
				"warning-light": "#FFD666",
				"warning-main": "#FFAB00",
				"warning-dark": "#B76E00",
				"warning-darker": "#7A4100",
				"error-lighter": "#FFE9D5",
				"error-light": "#FFAC82",
				"error-main": "#FF5630",
				"error-dark": "#B71D18",
				"error-darker": "#7A0916",
				"grey-0": "#FFFFFF",
				"grey-100": "#F9FAFB",
				"grey-200": "#F4F6F8",
				"grey-300": "#DFE3E8",
				"grey-400": "#C4CDD5",
				"grey-500": "#919EAB",
				"grey-600": "#637381",
				"grey-700": "#454F5B",
				"grey-800": "#212B36",
				"grey-900": "#161C24",
				"light-primary-text": "#212B36",
				"light-secondary-text": "#637381",
				"light-disabled-text": "#919EAB",
				"light-background-paper": "#ffffff",
				"light-background-default": "#F9FAFB",
				"light-background-natural": "#F4F6F8",
			},
		},
	},
	plugins: [require("tailwindcss-animate")],
} satisfies Config;

export default config;
